###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
general:

  productiveBranch: 'main'

# Stage configuration

stages:
 cloudFoundryDeploy:
    deployTool: 'cf_native'
    cloudFoundry:
      org: 'b81a0ed9trial'
      space: 'dev'
      credentialsId: 'Sofia2010'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
  #productionDeployment:
  #  cfTargets:
  #    - org: 'b81a0ed9trial'
  #      space: 'dev'
  #      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
  #      appName: 'CDSTest-srv'
  #      credentialsId: Sofia2010
#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

#  Release:
#    cfTargets:
#      - org: 'myOrg'
#        space: 'mySpace'
#        apiEndpoint: 'https://'
#        appName: 'myAppName'
#        manifest: 'manifest.yml'
#        credentialsId: 'myDeploymentCredentialsId'
